version: '3.8'

services:
  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: catalogo_online
    ports:
      - '5432:5432'
    volumes:
      - ./db-data:/var/lib/postgresql/data