services:
  db:
    image: postgres:17.5
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ProductShowcase
    ports:
      - '5432:5432'
    volumes:
      - ./db-data:/var/lib/postgresql/data